import { defineArrayMember, defineField, defineType } from "sanity";

export default defineType({
    name:"page",
    type:"document",
    title:"Page",
    i18n:true,

    fields:[
        defineField({
            title:"Title",
            name:"title",
            type:"string"
        }),
        defineField({
        title:"Sections",
        name:"sections",
        type:"array",
        of:[
            defineArrayMember({
                type:"carousel",
            }),
            defineArrayMember({
                type:"clients",
            }),
            defineArrayMember({
                type:"cta",
            }),
            defineArrayMember({
                type:"features",
            }),
            defineArrayMember({
                type:"footer",
            }),
            defineArrayMember({
                type:"goals",
            }),
            defineArrayMember({
                type:"header",
            }),
            defineArrayMember({
                type:"hero",
            }),
            defineArrayMember({
                type:"hero_featured_products",
            }),
            defineArrayMember({
                type:"how_does_it_work",
            }),
            defineArrayMember({
                type:"leadership",
            }),
            defineArrayMember({
                type:"notification",
            }),
            defineArrayMember({
                type:"testimonials",
            }),
            defineArrayMember({
                type:"video",
            }),
        ]
    })]
})